# Generated by Django 5.1 on 2024-08-27 09:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='description',
            field=models.TextField(help_text='Enter the description of the study', null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='study',
            name='number_of_places',
            field=models.IntegerField(default=1, help_text='Enter the number of places in the study', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5000)], verbose_name='Number of Places'),
        ),
        migrations.AddField(
            model_name='study',
            name='reward',
            field=models.IntegerField(default=10, help_text='Enter the reward for participating in the study', validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(10000)], verbose_name='Reward'),
        ),
        migrations.AlterField(
            model_name='study',
            name='name',
            field=models.CharField(help_text='Enter the name of the study', max_length=255, verbose_name='Study Name'),
        ),
    ]
