# Generated by Django 5.1 on 2024-08-27 09:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0002_study_description_study_number_of_places_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='creator',
            field=models.ForeignKey(default=1, help_text='Enter the creator of the study', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creator'),
            preserve_default=False,
        ),
    ]
